# Generated by Django 5.0.3 on 2024-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
