# Generated by Django 5.0.3 on 2024-03-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_student_city'),
    ]

    operations = [
    ]
